[package]
name = "optimizers"
version = "0.1.0"
authors = ["Chun Kai Ling <ckling@fb.com>"]
edition = "2018"

[lib]
name = "optimizers"
path = "optimizers.rs"

[dependencies]
libc = "0.2.0"

[build-dependencies]
bindgen = "0.49.2"